---
- name: maria db 10 repo
  yum_repository:
    name: MariaDB
    description: Maria DB 10
    baseurl: http://yum.mariadb.org/10.0/centos6-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: Install MariaDB packages
  yum: name={{ item }} state=installed
  with_items:
    - mariadb-server
    - MySQL-python

- name: Create MariaDB configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mariadb

- name: Create MariaDB log file
  file: path={{ mysql_log }} state=touch owner=mysql group=mysql mode=0775

- name: Create MariaDB PID directory
  file: path={{ mysql_pid_dir }} state=directory owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mysql state=started enabled=yes

- include_tasks: mysql_secure_installation.yml
- include_tasks: databases.yml


